api:
  - changed-files:
      - any-glob-to-any-file: "api/**"

web:
  - changed-files:
      - any-glob-to-any-file: "web/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "docker-compose*.yml"
          - "**/Dockerfile*"
          - ".dockerignore"

helm:
  - changed-files:
      - any-glob-to-any-file: "helm/**"
