{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.metadata.name | default (include "echostats.fullname" .) }}
  {{- if .Values.ingressRoute.metadata.namespace }}
  namespace: {{ .Values.ingressRoute.metadata.namespace }}
  {{- end }}
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressRoute.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
