{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "echostats.fullname" . }}
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - match: {{ .match | quote }}
      kind: Rule
      services:
        - name: {{ include "echostats.fullname" $ }}-{{ .service }}
          port: {{ if eq .service "api" }}{{ $.Values.service.api.port }}{{ else }}{{ $.Values.service.web.port }}{{ end }}
    {{- end }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- with .Values.ingressRoute.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
