{{- if .Values.pdb.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "echostats.fullname" . }}-api
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.pdb.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "echostats.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.pdb.web.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "echostats.fullname" . }}-web
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.pdb.web.minAvailable }}
  selector:
    matchLabels:
      {{- include "echostats.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
