apiVersion: v1
kind: Secret
metadata:
  name: {{ include "echostats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPOTIFY_CLIENT_ID: {{ .Values.spotify.clientId | quote }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.spotify.clientSecret | quote }}
  JWT_SECRET: {{ .Values.security.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.security.encryptionKey | quote }}
  {{- if .Values.mongodb.enabled }}
  MONGO_URI: "mongodb://{{ .Values.mongodb.auth.rootUsername }}:{{ .Values.mongodb.auth.rootPassword }}@{{ include "echostats.fullname" . }}-mongodb:27017/{{ .Values.mongodb.auth.database }}?authSource=admin"
  {{- else }}
  MONGO_URI: {{ .Values.mongodb.external.uri | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "echostats.fullname" . }}-redis:6379/0"
  {{- else }}
  REDIS_URL: {{ .Values.redis.external.url | quote }}
  {{- end }}
