apiVersion: v1
kind: Service
metadata:
  name: {{ include "echostats.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "echostats.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echostats.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
  selector:
    {{- include "echostats.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
