apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echostats.fullname" . }}-web
  labels:
    {{- include "echostats.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      {{- include "echostats.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "echostats.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "echostats.fullname" .) }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "echostats.fullname" . }}
            - secretRef:
                name: {{ include "echostats.fullname" . }}
          env:
            - name: INTERNAL_API_URL
              value: "http://{{ include "echostats.fullname" . }}-api:{{ .Values.api.port }}"
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.web.apiUrl | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
